const genviiPokemon = {
    "Meltan":{
        type1:"steel",
        "stats":[
            {
                "base_stat":46
            },
            {
                "base_stat":65
            },
            {
                "base_stat":65
            },
            {
                "base_stat":55
            },
            {
                "base_stat":35
            },
            {
                "base_stat":34
            },
        ]
    },
    "Melmetal":{
        type1:"steel",
        "stats":[
            {
                "base_stat":135
            },
            {
                "base_stat":143
            },
            {
                "base_stat":143
            },
            {
                "base_stat":80
            },
            {
                "base_stat":65
            },
            {
                "base_stat":34
            },
        ]
    },
    "Grookey":{
        type1:"grass",
        "stats":[
           {
              "base_stat":50
           },
           {
              "base_stat":65
           },
           {
              "base_stat":50
           },
           {
              "base_stat":40
           },
           {
              "base_stat":40
           },
           {
              "base_stat":65
           }
        ]
     },
     "Thwackey":{
        type1:"grass",
        "stats":[
           {
              "base_stat":70
           },
           {
              "base_stat":85
           },
           {
              "base_stat":70
           },
           {
              "base_stat":55
           },
           {
              "base_stat":60
           },
           {
              "base_stat":80
           }
        ]
     },
     "Rillaboom":{
        type1:"grass",
        "stats":[
           {
              "base_stat":100
           },
           {
              "base_stat":125
           },
           {
              "base_stat":90
           },
           {
              "base_stat":60
           },
           {
              "base_stat":70
           },
           {
              "base_stat":85
           }
        ]
     },
     "Scorbunny":{
        type1:"fire",
        "stats":[
           {
              "base_stat":50
           },
           {
              "base_stat":71
           },
           {
              "base_stat":40
           },
           {
              "base_stat":40
           },
           {
              "base_stat":40
           },
           {
              "base_stat":69
           }
        ]
     },
     "Raboot":{
        type1:"fire",
        "stats":[
           {
              "base_stat":65
           },
           {
              "base_stat":86
           },
           {
              "base_stat":60
           },
           {
              "base_stat":55
           },
           {
              "base_stat":60
           },
           {
              "base_stat":94
           }
        ]
     },
     "Cinderace":{
        type1:"fire",
        "stats":[
           {
              "base_stat":80
           },
           {
              "base_stat":116
           },
           {
              "base_stat":75
           },
           {
              "base_stat":65
           },
           {
              "base_stat":75
           },
           {
              "base_stat":119
           }
        ]
     },
     "Sobble":{
        type1:"water",
        "stats":[
           {
              "base_stat":50
           },
           {
              "base_stat":40
           },
           {
              "base_stat":40
           },
           {
              "base_stat":70
           },
           {
              "base_stat":40
           },
           {
              "base_stat":70
           }
        ]
     },
     "Drizzile":{
        type1:"water",
        "stats":[
           {
              "base_stat":65
           },
           {
              "base_stat":60
           },
           {
              "base_stat":55
           },
           {
              "base_stat":95
           },
           {
              "base_stat":55
           },
           {
              "base_stat":90
           }
        ]
     },
     "Inteleon":{
        type1:"water",
        "stats":[
           {
              "base_stat":70
           },
           {
              "base_stat":85
           },
           {
              "base_stat":65
           },
           {
              "base_stat":125
           },
           {
              "base_stat":65
           },
           {
              "base_stat":120
           }
        ]
     },
     "Skwovet":{
        type1:"normal",
        "stats":[
           {
              "base_stat":70
           },
           {
              "base_stat":55
           },
           {
              "base_stat":55
           },
           {
              "base_stat":35
           },
           {
              "base_stat":35
           },
           {
              "base_stat":25
           }
        ]
     },
     "Greedent":{
        type1:"normal",
        "stats":[
           {
              "base_stat":120
           },
           {
              "base_stat":95
           },
           {
              "base_stat":95
           },
           {
              "base_stat":55
           },
           {
              "base_stat":75
           },
           {
              "base_stat":20
           }
        ]
     },
     "Rookidee":{
        type1:"flying",
        "stats":[
           {
              "base_stat":38
           },
           {
              "base_stat":47
           },
           {
              "base_stat":35
           },
           {
              "base_stat":33
           },
           {
              "base_stat":35
           },
           {
              "base_stat":57
           }
        ]
     },
     "Corvisquire":{
        type1:"flying",
        "stats":[
           {
              "base_stat":68
           },
           {
              "base_stat":67
           },
           {
              "base_stat":55
           },
           {
              "base_stat":43
           },
           {
              "base_stat":55
           },
           {
              "base_stat":77
           }
        ]
     },
     "Corviknight":{
        type1:"flying",
        type2:"steel",
        "stats":[
           {
              "base_stat":98
           },
           {
              "base_stat":87
           },
           {
              "base_stat":105
           },
           {
              "base_stat":53
           },
           {
              "base_stat":85
           },
           {
              "base_stat":67
           }
        ]
     },
     "Blipbug":{
        type1:"bug",
        "stats":[
           {
              "base_stat":25
           },
           {
              "base_stat":20
           },
           {
              "base_stat":20
           },
           {
              "base_stat":25
           },
           {
              "base_stat":45
           },
           {
              "base_stat":45
           }
        ]
     },
     "Dottler":{
        type1:"bug",
        type2:"psychic",
        "stats":[
           {
              "base_stat":50
           },
           {
              "base_stat":35
           },
           {
              "base_stat":80
           },
           {
              "base_stat":50
           },
           {
              "base_stat":90
           },
           {
              "base_stat":30
           }
        ]
     },
     "Orbeetle":{
        type1:"bug",
        type2:"psychic",
        "stats":[
           {
              "base_stat":60
           },
           {
              "base_stat":45
           },
           {
              "base_stat":110
           },
           {
              "base_stat":80
           },
           {
              "base_stat":120
           },
           {
              "base_stat":90
           }
        ]
     },
     "Nickit":{
        type1:"dark",
        "stats":[
           {
              "base_stat":40
           },
           {
              "base_stat":28
           },
           {
              "base_stat":28
           },
           {
              "base_stat":47
           },
           {
              "base_stat":52
           },
           {
              "base_stat":50
           }
        ]
     },
     "Thievul":{
        type1:"dark",
        "stats":[
           {
              "base_stat":70
           },
           {
              "base_stat":58
           },
           {
              "base_stat":58
           },
           {
              "base_stat":87
           },
           {
              "base_stat":92
           },
           {
              "base_stat":90
           }
        ]
     },
     "Gossifleur":{
        type1:"grass",
        "stats":[
           {
              "base_stat":40
           },
           {
              "base_stat":40
           },
           {
              "base_stat":60
           },
           {
              "base_stat":40
           },
           {
              "base_stat":60
           },
           {
              "base_stat":10
           }
        ]
     },
     "Eldegoss":{
        type1:"grass",
        "stats":[
           {
              "base_stat":60
           },
           {
              "base_stat":50
           },
           {
              "base_stat":90
           },
           {
              "base_stat":80
           },
           {
              "base_stat":120
           },
           {
              "base_stat":60
           }
        ]
     },
     "Wooloo":{
        type1:"normal",
        "stats":[
           {
              "base_stat":42
           },
           {
              "base_stat":40
           },
           {
              "base_stat":55
           },
           {
              "base_stat":40
           },
           {
              "base_stat":45
           },
           {
              "base_stat":48
           }
        ]
     },
     "Dubwool":{
        type1:"normal",
        "stats":[
           {
              "base_stat":72
           },
           {
              "base_stat":80
           },
           {
              "base_stat":100
           },
           {
              "base_stat":60
           },
           {
              "base_stat":90
           },
           {
              "base_stat":88
           }
        ]
     },
     "Chewtle":{
        type1:"water",
        "stats":[
           {
              "base_stat":50
           },
           {
              "base_stat":64
           },
           {
              "base_stat":50
           },
           {
              "base_stat":38
           },
           {
              "base_stat":38
           },
           {
              "base_stat":44
           }
        ]
     },
     "Drednaw":{
        type1:"water",
        type2:"rock",
        "stats":[
           {
              "base_stat":90
           },
           {
              "base_stat":115
           },
           {
              "base_stat":90
           },
           {
              "base_stat":48
           },
           {
              "base_stat":68
           },
           {
              "base_stat":74
           }
        ]
     },
     "Yamper":{
        type1:"electric",
        "stats":[
           {
              "base_stat":59
           },
           {
              "base_stat":45
           },
           {
              "base_stat":50
           },
           {
              "base_stat":40
           },
           {
              "base_stat":50
           },
           {
              "base_stat":26
           }
        ]
     },
     "Boltund":{
        type1:"electric",
        "stats":[
           {
              "base_stat":69
           },
           {
              "base_stat":90
           },
           {
              "base_stat":60
           },
           {
              "base_stat":90
           },
           {
              "base_stat":60
           },
           {
              "base_stat":121
           }
        ]
     },
     "Rolycoly":{
        type1:"rock",
        "stats":[
           {
              "base_stat":30
           },
           {
              "base_stat":40
           },
           {
              "base_stat":50
           },
           {
              "base_stat":40
           },
           {
              "base_stat":50
           },
           {
              "base_stat":30
           }
        ]
     },
     "Carkol":{
        type1:"rock",
        type2:"fire",
        "stats":[
           {
              "base_stat":80
           },
           {
              "base_stat":60
           },
           {
              "base_stat":90
           },
           {
              "base_stat":60
           },
           {
              "base_stat":70
           },
           {
              "base_stat":50
           }
        ]
     },
     "Coalossal":{
        type1:"rock",
        type2:"fire",
        "stats":[
           {
              "base_stat":110
           },
           {
              "base_stat":80
           },
           {
              "base_stat":120
           },
           {
              "base_stat":80
           },
           {
              "base_stat":90
           },
           {
              "base_stat":30
           }
        ]
     },
     "Applin":{
        type1:"grass",
        type2:"dragon",
        "stats":[
           {
              "base_stat":40
           },
           {
              "base_stat":40
           },
           {
              "base_stat":80
           },
           {
              "base_stat":40
           },
           {
              "base_stat":40
           },
           {
              "base_stat":20
           }
        ]
     },
     "Flapple":{
        type1:"grass",
        type2:"dragon",
        "stats":[
           {
              "base_stat":70
           },
           {
              "base_stat":110
           },
           {
              "base_stat":80
           },
           {
              "base_stat":95
           },
           {
              "base_stat":60
           },
           {
              "base_stat":70
           }
        ]
     },
     "Appletun":{
        type1:"grass",
        type2:"dragon",
        "stats":[
           {
              "base_stat":110
           },
           {
              "base_stat":85
           },
           {
              "base_stat":80
           },
           {
              "base_stat":100
           },
           {
              "base_stat":80
           },
           {
              "base_stat":30
           }
        ]
     },
     "Silicobra":{
        type1:"ground",
        "stats":[
           {
              "base_stat":52
           },
           {
              "base_stat":57
           },
           {
              "base_stat":75
           },
           {
              "base_stat":35
           },
           {
              "base_stat":50
           },
           {
              "base_stat":46
           }
        ]
     },
     "Sandaconda":{
        type1:"ground",
        "stats":[
           {
              "base_stat":72
           },
           {
              "base_stat":107
           },
           {
              "base_stat":125
           },
           {
              "base_stat":65
           },
           {
              "base_stat":70
           },
           {
              "base_stat":71
           }
        ]
     },
     "Cramorant":{
        type1:"flying",
        type2:"water",
        "stats":[
           {
              "base_stat":70
           },
           {
              "base_stat":85
           },
           {
              "base_stat":55
           },
           {
              "base_stat":85
           },
           {
              "base_stat":95
           },
           {
              "base_stat":85
           }
        ]
     },
     "Arrokuda":{
        type1:"water",
        "stats":[
           {
              "base_stat":41
           },
           {
              "base_stat":63
           },
           {
              "base_stat":40
           },
           {
              "base_stat":40
           },
           {
              "base_stat":30
           },
           {
              "base_stat":66
           }
        ]
     },
     "Barraskewda":{
        type1:"water",
        "stats":[
           {
              "base_stat":61
           },
           {
              "base_stat":123
           },
           {
              "base_stat":60
           },
           {
              "base_stat":60
           },
           {
              "base_stat":50
           },
           {
              "base_stat":136
           }
        ]
     },
     "Toxel":{
        type1:"electric",
        type2:"poison",
        "stats":[
           {
              "base_stat":40
           },
           {
              "base_stat":38
           },
           {
              "base_stat":35
           },
           {
              "base_stat":54
           },
           {
              "base_stat":35
           },
           {
              "base_stat":40
           }
        ]
     },
     "Toxtricity":{
        type1:"electric",
        type2:"poison",
        "stats":[
           {
              "base_stat":75
           },
           {
              "base_stat":98
           },
           {
              "base_stat":70
           },
           {
              "base_stat":114
           },
           {
              "base_stat":70
           },
           {
              "base_stat":75
           }
        ]
     },
     "Sizzlipede":{
        type1:"fire",
        type2:"bug",
        "stats":[
           {
              "base_stat":50
           },
           {
              "base_stat":65
           },
           {
              "base_stat":45
           },
           {
              "base_stat":50
           },
           {
              "base_stat":50
           },
           {
              "base_stat":45
           }
        ]
     },
     "Centiskorch":{
        type1:"fire",
        type2:"bug",
        "stats":[
           {
              "base_stat":100
           },
           {
              "base_stat":115
           },
           {
              "base_stat":65
           },
           {
              "base_stat":90
           },
           {
              "base_stat":90
           },
           {
              "base_stat":65
           }
        ]
     },
     "Clobbopus":{
        type1:"fighting",
        "stats":[
           {
              "base_stat":50
           },
           {
              "base_stat":68
           },
           {
              "base_stat":60
           },
           {
              "base_stat":50
           },
           {
              "base_stat":50
           },
           {
              "base_stat":32
           }
        ]
     },
     "Grapploct":{
        type1:"fighting",
        "stats":[
           {
              "base_stat":80
           },
           {
              "base_stat":118
           },
           {
              "base_stat":90
           },
           {
              "base_stat":70
           },
           {
              "base_stat":80
           },
           {
              "base_stat":42
           }
        ]
     },
     "Sinistea":{
        type1:"ghost",
        "stats":[
           {
              "base_stat":40
           },
           {
              "base_stat":45
           },
           {
              "base_stat":45
           },
           {
              "base_stat":74
           },
           {
              "base_stat":54
           },
           {
              "base_stat":50
           }
        ]
     },
     "Polteageist":{
        type1:"ghost",
        "stats":[
           {
              "base_stat":60
           },
           {
              "base_stat":65
           },
           {
              "base_stat":65
           },
           {
              "base_stat":134
           },
           {
              "base_stat":114
           },
           {
              "base_stat":70
           }
        ]
     },
     "Hatenna":{
        type1:"psychic",
        "stats":[
           {
              "base_stat":42
           },
           {
              "base_stat":30
           },
           {
              "base_stat":45
           },
           {
              "base_stat":56
           },
           {
              "base_stat":53
           },
           {
              "base_stat":39
           }
        ]
     },
     "Hattrem":{
        type1:"psychic",
        "stats":[
           {
              "base_stat":57
           },
           {
              "base_stat":40
           },
           {
              "base_stat":65
           },
           {
              "base_stat":86
           },
           {
              "base_stat":73
           },
           {
              "base_stat":49
           }
        ]
     },
     "Hatterene":{
        type1:"psychic",
        type2:"fairy",
        "stats":[
           {
              "base_stat":57
           },
           {
              "base_stat":90
           },
           {
              "base_stat":95
           },
           {
              "base_stat":136
           },
           {
              "base_stat":103
           },
           {
              "base_stat":29
           }
        ]
     },
     "Impidimp":{
        type1:"dark",
        type2:"fairy",
        "stats":[
           {
              "base_stat":45
           },
           {
              "base_stat":45
           },
           {
              "base_stat":30
           },
           {
              "base_stat":55
           },
           {
              "base_stat":40
           },
           {
              "base_stat":50
           }
        ]
     },
     "Morgrem":{
        type1:"dark",
        type2:"fairy",
        "stats":[
           {
              "base_stat":65
           },
           {
              "base_stat":60
           },
           {
              "base_stat":45
           },
           {
              "base_stat":75
           },
           {
              "base_stat":55
           },
           {
              "base_stat":70
           }
        ]
     },
     "Grimmsnarl":{
        type1:"dark",
        type2:"fairy",
        "stats":[
           {
              "base_stat":95
           },
           {
              "base_stat":120
           },
           {
              "base_stat":65
           },
           {
              "base_stat":95
           },
           {
              "base_stat":75
           },
           {
              "base_stat":60
           }
        ]
     },
     "Zigzagoon-galar":{
        type1:"dark",
        type2:"normal",
        "stats":[
           {
              "base_stat":38
           },
           {
              "base_stat":30
           },
           {
              "base_stat":41
           },
           {
              "base_stat":30
           },
           {
              "base_stat":41
           },
           {
              "base_stat":60
           }
        ]
     },
     "Linoone-galar":{
        type1:"dark",
        type2:"normal",
        "stats":[
           {
              "base_stat":78
           },
           {
              "base_stat":70
           },
           {
              "base_stat":61
           },
           {
              "base_stat":50
           },
           {
              "base_stat":61
           },
           {
              "base_stat":100
           }
        ]
     },
     "Obstagoon":{
        type1:"dark",
        type2:"normal",
        "stats":[
           {
              "base_stat":93
           },
           {
              "base_stat":90
           },
           {
              "base_stat":101
           },
           {
              "base_stat":60
           },
           {
              "base_stat":81
           },
           {
              "base_stat":95
           }
        ]
     },
     "Perrserker":{
        type1:"steel",
        "stats":[
           {
              "base_stat":70
           },
           {
              "base_stat":110
           },
           {
              "base_stat":100
           },
           {
              "base_stat":50
           },
           {
              "base_stat":60
           },
           {
              "base_stat":50
           }
        ]
     },
     "Cursola":{
        type1:"ghost",
        "stats":[
           {
              "base_stat":60
           },
           {
              "base_stat":95
           },
           {
              "base_stat":50
           },
           {
              "base_stat":145
           },
           {
              "base_stat":130
           },
           {
              "base_stat":30
           }
        ]
     },
     "Farfetchd-galar":{
        type1:"fighting",
        "stats":[
           {
              "base_stat":52
           },
           {
              "base_stat":95
           },
           {
              "base_stat":55
           },
           {
              "base_stat":58
           },
           {
              "base_stat":62
           },
           {
              "base_stat":55
           }
        ]
     },
     "Sirfetchd":{
        type1:"fighting",
        "stats":[
           {
              "base_stat":62
           },
           {
              "base_stat":135
           },
           {
              "base_stat":95
           },
           {
              "base_stat":68
           },
           {
              "base_stat":82
           },
           {
              "base_stat":65
           }
        ]
     },
     "Mr-Mime-galar":{
        type1:"ice",
        type2:"psychic",
        "stats":[
           {
              "base_stat":50
           },
           {
              "base_stat":65
           },
           {
              "base_stat":65
           },
           {
              "base_stat":90
           },
           {
              "base_stat":90
           },
           {
              "base_stat":100
           }
        ]
     },
     "Mr-Rime":{
        type1:"ice",
        type2:"psychic",
        "stats":[
           {
              "base_stat":80
           },
           {
              "base_stat":85
           },
           {
              "base_stat":75
           },
           {
              "base_stat":110
           },
           {
              "base_stat":100
           },
           {
              "base_stat":70
           }
        ]
     },
     "Yamask-galar":{
        type1:"ground",
        type2:"ghost",
        "stats":[
           {
              "base_stat":38
           },
           {
              "base_stat":55
           },
           {
              "base_stat":85
           },
           {
              "base_stat":30
           },
           {
              "base_stat":65
           },
           {
              "base_stat":30
           }
        ]
     },
     "Runerigus":{
        type1:"ground",
        type2:"ghost",
        "stats":[
           {
              "base_stat":58
           },
           {
              "base_stat":95
           },
           {
              "base_stat":145
           },
           {
              "base_stat":50
           },
           {
              "base_stat":105
           },
           {
              "base_stat":30
           }
        ]
     },
     "Milcery":{
        type1:"fairy",
        "stats":[
           {
              "base_stat":45
           },
           {
              "base_stat":40
           },
           {
              "base_stat":40
           },
           {
              "base_stat":50
           },
           {
              "base_stat":61
           },
           {
              "base_stat":34
           }
        ]
     },
     "Alcremie":{
        type1:"fairy",
        "stats":[
           {
              "base_stat":65
           },
           {
              "base_stat":60
           },
           {
              "base_stat":75
           },
           {
              "base_stat":110
           },
           {
              "base_stat":121
           },
           {
              "base_stat":64
           }
        ]
     },
     "Falinks":{
        type1:"fighting",
        "stats":[
           {
              "base_stat":65
           },
           {
              "base_stat":100
           },
           {
              "base_stat":100
           },
           {
              "base_stat":70
           },
           {
              "base_stat":60
           },
           {
              "base_stat":75
           }
        ]
     },
     "Pincurchin":{
        type1:"electric",
        "stats":[
           {
              "base_stat":48
           },
           {
              "base_stat":101
           },
           {
              "base_stat":95
           },
           {
              "base_stat":91
           },
           {
              "base_stat":85
           },
           {
              "base_stat":15
           }
        ]
     },
     "Snom":{
        type1:"ice",
        type2:"bug",
        "stats":[
           {
              "base_stat":30
           },
           {
              "base_stat":25
           },
           {
              "base_stat":35
           },
           {
              "base_stat":45
           },
           {
              "base_stat":30
           },
           {
              "base_stat":20
           }
        ]
     },
     "Frosmoth":{
        type1:"ice",
        type2:"bug",
        "stats":[
           {
              "base_stat":70
           },
           {
              "base_stat":65
           },
           {
              "base_stat":60
           },
           {
              "base_stat":125
           },
           {
              "base_stat":90
           },
           {
              "base_stat":65
           }
        ]
     },
     "Stonjourner":{
        type1:"rock",
        "stats":[
           {
              "base_stat":100
           },
           {
              "base_stat":125
           },
           {
              "base_stat":135
           },
           {
              "base_stat":20
           },
           {
              "base_stat":20
           },
           {
              "base_stat":70
           }
        ]
     },
     "Eiscue":{
        type1:"ice",
        "stats":[
           {
              "base_stat":75
           },
           {
              "base_stat":80
           },
           {
              "base_stat":110
           },
           {
              "base_stat":65
           },
           {
              "base_stat":90
           },
           {
              "base_stat":50
           }
        ]
     },
     "Indeedee":{
        type1:"psychic",
        type2:"normal",
        "stats":[
           {
              "base_stat":60
           },
           {
              "base_stat":65
           },
           {
              "base_stat":55
           },
           {
              "base_stat":105
           },
           {
              "base_stat":95
           },
           {
              "base_stat":95
           }
        ]
     },
     "Morpeko":{
        type1:"electric",
        type2:"dark",
        "stats":[
           {
              "base_stat":58
           },
           {
              "base_stat":95
           },
           {
              "base_stat":58
           },
           {
              "base_stat":70
           },
           {
              "base_stat":58
           },
           {
              "base_stat":97
           }
        ]
     },
     "Cufant":{
        type1:"steel",
        "stats":[
           {
              "base_stat":72
           },
           {
              "base_stat":80
           },
           {
              "base_stat":49
           },
           {
              "base_stat":40
           },
           {
              "base_stat":49
           },
           {
              "base_stat":40
           }
        ]
     },
     "Copperajah":{
        type1:"steel",
        "stats":[
           {
              "base_stat":122
           },
           {
              "base_stat":130
           },
           {
              "base_stat":69
           },
           {
              "base_stat":80
           },
           {
              "base_stat":69
           },
           {
              "base_stat":30
           }
        ]
     },
     "Dracozolt":{
        type1:"electric",
        type2:"dragon",
        "stats":[
           {
              "base_stat":90
           },
           {
              "base_stat":100
           },
           {
              "base_stat":90
           },
           {
              "base_stat":80
           },
           {
              "base_stat":70
           },
           {
              "base_stat":75
           }
        ]
     },
     "Arctozolt":{
        type1:"electric",
        type2:"ice",
        "stats":[
           {
              "base_stat":90
           },
           {
              "base_stat":100
           },
           {
              "base_stat":90
           },
           {
              "base_stat":90
           },
           {
              "base_stat":80
           },
           {
              "base_stat":55
           }
        ]
     },
     "Dracovish":{
        type1:"water",
        type2:"dragon",
        "stats":[
           {
              "base_stat":90
           },
           {
              "base_stat":90
           },
           {
              "base_stat":100
           },
           {
              "base_stat":70
           },
           {
              "base_stat":80
           },
           {
              "base_stat":75
           }
        ]
     },
     "Arctovish":{
        type1:"water",
        type2:"ice",
        "stats":[
           {
              "base_stat":90
           },
           {
              "base_stat":90
           },
           {
              "base_stat":100
           },
           {
              "base_stat":80
           },
           {
              "base_stat":90
           },
           {
              "base_stat":55
           }
        ]
     },
     "Duraludon":{
        type1:"steel",
        type2:"dragon",
        "stats":[
           {
              "base_stat":70
           },
           {
              "base_stat":95
           },
           {
              "base_stat":115
           },
           {
              "base_stat":120
           },
           {
              "base_stat":50
           },
           {
              "base_stat":85
           }
        ]
     },
     "Dreepy":{
        type1:"dragon",
        type2:"ghost",
        "stats":[
           {
              "base_stat":28
           },
           {
              "base_stat":60
           },
           {
              "base_stat":30
           },
           {
              "base_stat":40
           },
           {
              "base_stat":30
           },
           {
              "base_stat":82
           }
        ]
     },
     "Drakloak":{
        type1:"dragon",
        type2:"ghost",
        "stats":[
           {
              "base_stat":68
           },
           {
              "base_stat":80
           },
           {
              "base_stat":50
           },
           {
              "base_stat":60
           },
           {
              "base_stat":50
           },
           {
              "base_stat":102
           }
        ]
     },
     "Dragapult":{
        type1:"dragon",
        type2:"ghost",
        "stats":[
           {
              "base_stat":88
           },
           {
              "base_stat":120
           },
           {
              "base_stat":75
           },
           {
              "base_stat":100
           },
           {
              "base_stat":75
           },
           {
              "base_stat":142
           }
        ]
     },
     "Zacian":{
        type1:"fairy",
        "stats":[
           {
              "base_stat":92
           },
           {
              "base_stat":130
           },
           {
              "base_stat":115
           },
           {
              "base_stat":80
           },
           {
              "base_stat":115
           },
           {
              "base_stat":138
           }
        ]
     },
     "Zacian-crowned":{
        type1:"fairy",
        type2:"steel",
        "stats":[
           {
              "base_stat":92
           },
           {
              "base_stat":170
           },
           {
              "base_stat":115
           },
           {
              "base_stat":80
           },
           {
              "base_stat":115
           },
           {
              "base_stat":148
           }
        ]
     },
     "Zamazenta":{
        type1:"fighting",
        "stats":[
           {
              "base_stat":92
           },
           {
              "base_stat":130
           },
           {
              "base_stat":115
           },
           {
              "base_stat":80
           },
           {
              "base_stat":115
           },
           {
              "base_stat":138
           }
        ]
     },
     "Zamazenta-crowned":{
        type1:"fighting",
        type2:"steel",
        "stats":[
           {
              "base_stat":92
           },
           {
              "base_stat":130
           },
           {
              "base_stat":145
           },
           {
              "base_stat":80
           },
           {
              "base_stat":145
           },
           {
              "base_stat":128
           }
        ]
     },
     "Eternatus":{
        type1:"poison",
        type2:"dragon",
        "stats":[
           {
              "base_stat":140
           },
           {
              "base_stat":85
           },
           {
              "base_stat":95
           },
           {
              "base_stat":145
           },
           {
              "base_stat":95
           },
           {
              "base_stat":130
           }
        ]
     }
};

export default genviiPokemon;